#version 460 core
layout( local_size_x = 1) in;

layout(std430, binding = 1) buffer cellPosition_buf
{
	vec4 cellPosition[];
};

layout(std430, binding = 2) buffer cellValue_buf
{
	vec4 cellValue[];
};

layout(std430, binding = 3) buffer vertex_buf
{
	vec4 vertex[];
};

layout(std430, binding = 4) buffer face_buf
{
	vec4 face[];
};

layout(std430, binding = 5) buffer normal_buf
{
	vec4 normal[];
};

void main(void) {
	uint i = gl_GlobalInvocationID.x;

}


